- hosts: database
  become: true
  tasks:
    - name: " create a sotfware repository "
      template:
        src: templates/mysql-community.j2
        dest: /etc/yum.repos.d/mysql80-community.repo
        owner: root
